### PR TITLE
Event

### PR DESCRIPTION
**Pull request by DanteAlonsoHT**
<h1> Private events - Associations </h1>

In this project, we build a private event web app where members can register attendance for an event or being able to create an event. Inside this app, members can see a list of past and upcoming events, if the customer is not already logged out they can only see the entire list, but they can't create or register attendance. You can find in this project relations among three tables to register users, events, and attendance.

In our project we consider adding the next sections:

Users, Events, Attendances tables
Users, Events, Attendances models
Users, Events, Attendances controllers
Views for Events, only for some methods.
Linters
License
Descriptive README.md
Finally, we completed successfully, having no error in linters :)

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
---------------
Hello @DanteAlonsoHT @Fondem-Jr, great job you did in this project :clap: :100: 
TO HIGHLIGHT: 

- Great job working on the design
- The app looks good 
- The repo is professional
- The project looks professional 
- Excellent use of the MVP
- Well structured files 
However, there are a few changes to make to complete this project :hammer_and_wrench: see them below :eyes: :point_down: 
-----------------
- [x] The event show page shows a list of the attendance. 

events_attendees_requirement

Right now the app does not show the list. 

Screenshot from 2021-06-23 15-19-55
 

- [x] The same user can attend the same event as many times the user wants. 
- [x] A user that is not the owner of the event, can destroy and edit the event. Please make sure only the owner can modify the event. 
- [x] There must be a user's show page, that displays events the user has created and events that the user is attending to separated in past and upcoming.
 
user_events_requirement

- [x] In your `create`  action in `events_controller.rb` use `#build` [association refrence method](https://guides.rubyonrails.org/association_basics.html#detailed-association-reference). E.g `current_user.events.build(event_params)` to create the new event with the user’s ID prepopulated.

build_method_requirement

- [x] In the `index` action Lists past events, E.g  `@past_events = Event.previous_events`. Also upcoming events, E.g  `@upcoming_events = Event.upcoming_events`

past_upcoming_events_requirement

- [x] Please add the `show` action on the users_controller. Lists events created by user, E.g `@created_events = current_user.events`

current_user_show_requirement

Lists events previoulsy attendented by user **using event model scope**, e.g  `@past_events = current_user.attended_events.previous` and upcoming events previously attended by user **using event model scope**, e.g  `@upcoming_events = current_user.attended_events.upcoming`

user_events_requirement (1)

- [x] There is an event controller that you are not using please delete it. 
------------- 
Please make these required changes and send it again for another review :clap: :smile: 
HAPPY CODING!!!

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes required 🔴 
Nice job implementing almost all the changes requested by the previous reviewer.
**To highlight**

- You have created users show page.
- You have past and upcoming events on the users' show page.
- A user can't edit or delete other users' posts.
- In the post controller create method, you have used build.

**Changes to make**

- [x] When I attempt to click the attend event link, I get the error in the image below.
attendance
<hr>
When you are done, submit another review request.

In case you have a question about this review, please reach out to me through the comment section in this same PR.
# Happy coding💪✔

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- User can attend an event :+1: 

To improve :factory_worker: [REQUIRED]:

- [x] I got an error when I click on `Go to see past and upcoming events` when I am not logged in: 


- [x] The same user can attend the same event as many times the user wants.


- [x] The user's show page displays events the user has created `and events that the user is attending to separated in past and upcoming`  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). In your APP the user's show page displays only events created by the user. For example in the screenshot below, the event `Josia past` should appear in the user's show page of Marina as Marina attends it many times:


Nice to have [OPTIONAL] :

- [ ] Models have unit tests for validations and associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ] Authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ] Event management features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ] It will be nice if there are no logic in your views

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by cyonii — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED ♻️✍️

Keep up the energy. 

#### TO IMPROVE (REQUIRED)
You have done great so far, but these few issues need to be fixed in order to get your project approved. Kindly fix them and resubmit.
- [x] Two users cannot attend the same event. The button to attend an event disappears after one user joins, and goes on to display "You are already registered for this event" to all users.
- [x] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)). Currently I can't find your user #show view. Please add this.

#### NICE TO HAVE
Note that these are not mandatory, but I encourage you to implement them.
- [ ] You should remove all logic in view, use helper methods for your logic.

> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Changes Required :yellow_circle:            
### Hello @Fondem-Jr and @DanteAlonsoHT  :wave: 

Your project looks good and shows you have put effort into it:
#### To highlight
- good use of tables to present events in a tabular form
- descriptive README and pull request description


Thanks for working on the requirements suggested by previous reviewers and kindly make sure to work on the following missing requirements:
#### To improve
- as the previous reviewer suggested, please include a link(button) to a user show page as specified [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png), currently no link is available to get to a user show page, even though a route to `user/show` is added.

#### If you have any question feel free to ask within the PR and ping me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)#

**Review by MkrtichSargsyan — APPROVED** [review]
## _Status:_ Approved  :hamster: :rocket:
Hello :wave:.

Awesome job on this project.:rocket: You have completed all the requested changes from the previous code reviewer.

You can go ahead and merge this branch to the base branch of this repo.
Good luck in your future projects and happy coding :relaxed:

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Pull request merged**
